#!/usr/bin/gawk -f
# Convert a CSV portal file into an IITC drawtools set of markers
BEGIN { FS=","; printf("["); }
NR==1 && /^Name/ { next }
{ if (tail) printf(","); else tail = 1;
  printf("{\"type\":\"marker\",\"latLng\":{\"lat\":%s,\"lng\":%s},\"color\":\"#a24ac3\"}", $2, $3);
}
END { print "]" }
